#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libnetfilter_cttimeout
Version  : 1.0.0
Release  : 5
URL      : http://netfilter.org/projects/libnetfilter_cttimeout/files/libnetfilter_cttimeout-1.0.0.tar.bz2
Source0  : http://netfilter.org/projects/libnetfilter_cttimeout/files/libnetfilter_cttimeout-1.0.0.tar.bz2
Summary  : Netfilter extended cttimeout infrastructure library
Group    : Development/Tools
License  : GPL-2.0
Requires: libnetfilter_cttimeout-lib
BuildRequires : pkgconfig(libmnl)

%description
= cttimeout: timeout policy tuning for Netfilter/conntrack =
This infrastructure allows you to define fine-grain timeout
policies per flow. Basically, from user-space, you can create
timeout policy objects via nfct_timeout_alloc(), set the
policy attributes, via nfct_timeout_*_attr_set(), and then
build the ctnetlink message to communicate this new timeout
policy to the kernel.

%package dev
Summary: dev components for the libnetfilter_cttimeout package.
Group: Development
Requires: libnetfilter_cttimeout-lib

%description dev
dev components for the libnetfilter_cttimeout package.


%package lib
Summary: lib components for the libnetfilter_cttimeout package.
Group: Libraries

%description lib
lib components for the libnetfilter_cttimeout package.


%prep
%setup -q -n libnetfilter_cttimeout-1.0.0

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libnetfilter_cttimeout/libnetfilter_cttimeout.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
