#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xA4111F89BB5F58CC (coreteam@netfilter.org)
#
Name     : libnetfilter_cttimeout
Version  : 1.0.0
Release  : 10
URL      : http://netfilter.org/projects/libnetfilter_cttimeout/files/libnetfilter_cttimeout-1.0.0.tar.bz2
Source0  : http://netfilter.org/projects/libnetfilter_cttimeout/files/libnetfilter_cttimeout-1.0.0.tar.bz2
Source1  : http://netfilter.org/projects/libnetfilter_cttimeout/files/libnetfilter_cttimeout-1.0.0.tar.bz2.sig
Summary  : Netfilter extended cttimeout infrastructure library
Group    : Development/Tools
License  : GPL-2.0
Requires: libnetfilter_cttimeout-lib = %{version}-%{release}
Requires: libnetfilter_cttimeout-license = %{version}-%{release}
BuildRequires : pkgconfig(libmnl)

%description
= cttimeout: timeout policy tuning for Netfilter/conntrack =
This infrastructure allows you to define fine-grain timeout
policies per flow. Basically, from user-space, you can create
timeout policy objects via nfct_timeout_alloc(), set the
policy attributes, via nfct_timeout_*_attr_set(), and then
build the ctnetlink message to communicate this new timeout
policy to the kernel.

%package dev
Summary: dev components for the libnetfilter_cttimeout package.
Group: Development
Requires: libnetfilter_cttimeout-lib = %{version}-%{release}
Provides: libnetfilter_cttimeout-devel = %{version}-%{release}
Requires: libnetfilter_cttimeout = %{version}-%{release}

%description dev
dev components for the libnetfilter_cttimeout package.


%package lib
Summary: lib components for the libnetfilter_cttimeout package.
Group: Libraries
Requires: libnetfilter_cttimeout-license = %{version}-%{release}

%description lib
lib components for the libnetfilter_cttimeout package.


%package license
Summary: license components for the libnetfilter_cttimeout package.
Group: Default

%description license
license components for the libnetfilter_cttimeout package.


%prep
%setup -q -n libnetfilter_cttimeout-1.0.0
cd %{_builddir}/libnetfilter_cttimeout-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1593109650
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1593109650
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libnetfilter_cttimeout
cp %{_builddir}/libnetfilter_cttimeout-1.0.0/COPYING %{buildroot}/usr/share/package-licenses/libnetfilter_cttimeout/075d599585584bb0e4b526f5c40cb6b17e0da35a
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libnetfilter_cttimeout/libnetfilter_cttimeout.h
/usr/lib64/libnetfilter_cttimeout.so
/usr/lib64/pkgconfig/libnetfilter_cttimeout.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnetfilter_cttimeout.so.1
/usr/lib64/libnetfilter_cttimeout.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libnetfilter_cttimeout/075d599585584bb0e4b526f5c40cb6b17e0da35a
